import Navbar from "@/app/components/nabar.js";
import Session from "@/app/components/session.js";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
  icons: {
    icon: "/globe.svg",
  },
};

export default async function MainLayout({ children }) {
  const session = await Session();
  return (
    <>
      <Navbar session={session} />
      <main>{children}</main>
    </>
  );
}
