import Navbar from "@/app/components/nabar";
import Session from "@/app/components/session";
import Footer from "@/app/components/footer";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
  icons: {
    icon: "/globe.svg",
  },
};

export default async function MainLayout({ children }) {
  const session = await Session();
  return (
    <>
      <header>
        <Navbar session={session} />
      </header>
      <main>{children}</main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
