import Navbar from "@/app/components/nabar.js";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
  icons: {
    icon: "/globe.svg",
  },
};

export default function MainLayout({ children }) {
  return (
    <>
      <Navbar />
      <main>{children}</main>
    </>
  );
}
